title: WEB Test
author:
    name: TL
    url: https://github.com/rod-men1020
email: your-email@domain.com
description: >
  Turing Laboratory belongs to a new generation of Research and Development laboratories recently inaugurated in Galileo University to promote the development of Science and Technology.
baseurl: ""
url: "http://turing.galileo.edu"

social:
    facebook: labturing
    github: turing-lab

# Build settings
markdown: kramdown
highlighter: rouge
